// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccessTokenInfo struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	IssueUnix            int64    `protobuf:"varint,2,opt,name=issueUnix,proto3" json:"issueUnix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenInfo) Reset()         { *m = AccessTokenInfo{} }
func (m *AccessTokenInfo) String() string { return proto.CompactTextString(m) }
func (*AccessTokenInfo) ProtoMessage()    {}
func (*AccessTokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AccessTokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenInfo.Unmarshal(m, b)
}
func (m *AccessTokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenInfo.Marshal(b, m, deterministic)
}
func (m *AccessTokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenInfo.Merge(m, src)
}
func (m *AccessTokenInfo) XXX_Size() int {
	return xxx_messageInfo_AccessTokenInfo.Size(m)
}
func (m *AccessTokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenInfo proto.InternalMessageInfo

func (m *AccessTokenInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AccessTokenInfo) GetIssueUnix() int64 {
	if m != nil {
		return m.IssueUnix
	}
	return 0
}

type RefreshTokenInfo struct {
	UserID               string   `protobuf:"bytes,5,opt,name=userID,proto3" json:"userID,omitempty"`
	IssueUnix            int64    `protobuf:"varint,6,opt,name=issueUnix,proto3" json:"issueUnix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenInfo) Reset()         { *m = RefreshTokenInfo{} }
func (m *RefreshTokenInfo) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenInfo) ProtoMessage()    {}
func (*RefreshTokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RefreshTokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenInfo.Unmarshal(m, b)
}
func (m *RefreshTokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenInfo.Marshal(b, m, deterministic)
}
func (m *RefreshTokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenInfo.Merge(m, src)
}
func (m *RefreshTokenInfo) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenInfo.Size(m)
}
func (m *RefreshTokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenInfo proto.InternalMessageInfo

func (m *RefreshTokenInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RefreshTokenInfo) GetIssueUnix() int64 {
	if m != nil {
		return m.IssueUnix
	}
	return 0
}

func init() {
	proto.RegisterType((*AccessTokenInfo)(nil), "auth.AccessTokenInfo")
	proto.RegisterType((*RefreshTokenInfo)(nil), "auth.RefreshTokenInfo")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xdc, 0xb9, 0xf8, 0x1d, 0x93,
	0x93, 0x53, 0x8b, 0x8b, 0x43, 0xf2, 0xb3, 0x53, 0xf3, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0xc4, 0xb8,
	0xd8, 0x4a, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c,
	0x21, 0x19, 0x2e, 0xce, 0xcc, 0xe2, 0xe2, 0xd2, 0xd4, 0xd0, 0xbc, 0xcc, 0x0a, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0xe6, 0x20, 0x84, 0x80, 0x92, 0x07, 0x97, 0x40, 0x50, 0x6a, 0x5a, 0x51, 0x6a, 0x71,
	0x06, 0x36, 0x93, 0x58, 0x71, 0x9b, 0xc4, 0x86, 0x66, 0x52, 0x12, 0x1b, 0xd8, 0x7d, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xbc, 0x32, 0xc1, 0xad, 0x00, 0x00, 0x00,
}
